# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # 定时任务，在每天的2,5点
    - cron: '10 18,21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Run a multi-line script
        run: |
          rm -rf *

      - name: Checkout lets
        uses: actions/checkout@v2
        with:
          repository: hehe413/lets
          token: ${{ secrets.ACCESS_TOKEN }}
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls
          cp ./account.json ~
          rm -rf *
      
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          echo `date` > ./.tmp_file.txt
          cp ~/account.json .
          ls -al
          git config --global user.email 403219317@qq.com
          git config --global user.name hehe413
          git add .
          git commit -m "update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  # update lets
  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout lets
      - name: Checkout lets
        uses: actions/checkout@v2
        with:
          repository: hehe413/lets
          token: ${{ secrets.ACCESS_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls
          echo "# lets" > ./README.md
          echo `date` >> ./README.md
          git config --global user.email 403219317@qq.com
          git config --global user.name hehe413
          git add .
          git commit -m "update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
